apiVersion: v1
kind: Pod
metadata:
    name: nginx-proxy-manager
    labels:
        app: nginx-proxy-manager
spec:
    restartPolicy: Always
    containers:
        - name: nginx-proxy-manager
          image: docker.io/jc21/nginx-proxy-manager:latest
          ports:
              - containerPort: 80
              - containerPort: 81
              - containerPort: 443
          env:
              - name: PUID
                value: "0"
              - name: PGID
                value: "0"
              - name: TZ
                value: "Asia/Shanghai"
          volumeMounts:
              - name: nginx-proxy-manager-data
                subPath: data
                mountPath: /data
              - name: nginx-proxy-manager-data
                subPath: letsencrypt
                mountPath: /etc/letsencrypt
    volumes:
        - name: nginx-proxy-manager-data
          persistentVolumeClaim:
              claimName: nginx-proxy-manager-data
