apiVersion: v1
kind: Pod
metadata:
    name: forgejo
    labels:
        app: forgejo
spec:
    restartPolicy: Always
    containers:
        - name: server
          image: docker.io/codeberg.org/forgejo/forgejo:latest
          ports:
              - containerPort: 22
                hostPort: 2222
              - containerPort: 3000
          env:
              - name: USER_UID
                value: "0"
              - name: USER_GID
                value: "0"
              - name: TZ
                value: "Asia/Shanghai"
          volumeMounts:
              - name: forgejo-data
                mountPath: /data
    volumes:
        - name: forgejo-data
          persistentVolumeClaim:
              claimName: forgejo-data
