apiVersion: v1
kind: Pod
metadata:
    name: seaweedfs-cluster
    labels:
        app: seaweedfs
spec:
    containers:
        # 1. Master 主控
        - name: master
          image: docker.io/chrislusf/seaweedfs:latest
          args: ["master", "-ip=localhost"]
          ports:
              - containerPort: 9333

        # 2. Volume 存储节点
        - name: volume
          image: docker.io/chrislusf/seaweedfs:latest
          args: ["volume", "-mserver=localhost:9333", "-port=8080", "-ip=localhost"]
          volumeMounts:
              - name: seaweed-data
                mountPath: /data

        # 3. Filer 浏览器
        - name: filer
          image: docker.io/chrislusf/seaweedfs:latest
          args: ["filer", "-master=localhost:9333"]
          ports:
              - containerPort: 8888
          volumeMounts:
              - name: seaweed-config
                subPath: filer.toml
                mountPath: /etc/seaweedfs/filer.toml
                readOnly: true

        # 4. S3 网关
        - name: s3
          image: docker.io/chrislusf/seaweedfs:latest
          args:
              [
                  "s3",
                  "-filer=localhost:8888",
                  "-ip.bind=0.0.0.0",
                  "-port=8333",
                  "-config=/etc/seaweedfs/s3.json",
              ]
          ports:
              - containerPort: 8333
          volumeMounts:
              - name: seaweed-config
                subPath: s3.json
                mountPath: /etc/seaweedfs/s3.json
                readOnly: true

        # 5. redis
        - name: redis
          image: docker.io/redis:7-alpine
          args: ["redis-server", "--appendonly", "yes"]
          ports:
              - containerPort: 6379
          volumeMounts:
              - name: seaweed-redis
                mountPath: /data

    volumes:
        - name: seaweed-data
          persistentVolumeClaim:
              claimName: seaweed-data
        - name: seaweed-config
          persistentVolumeClaim:
              claimName: seaweed-config
        - name: seaweed-redis
          persistentVolumeClaim:
              claimName: seaweed-redis
