---
apiVersion: v1
kind: ConfigMap
metadata:
    name: vaultwarden-env
data:
    TZ: Asia/Shanghai
    DOMAIN: https://vw.daveny.top

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: vaultwarden-data
spec:
    accessModes:
        - ReadWriteOnce
    resources:
        requests:
            storage: 5Gi

---
apiVersion: v1
kind: Pod
metadata:
    name: vaultwarden
    labels:
        app: vaultwarden
spec:
    restartPolicy: Always
    containers:
        - name: vaultwarden
          image: ghcr.io/hiromuraki/containerized-service/vaultwarden:latest
          envFrom:
              - configMapRef:
                    name: vaultwarden-env
          ports:
              - containerPort: 80
                hostPort: 3010
                hostIP: 127.0.0.1
          volumeMounts:
              - name: vaultwarden-data
                mountPath: /data/
    volumes:
        - name: vaultwarden-data
          persistentVolumeClaim:
              claimName: vaultwarden-data
