---
apiVersion: v1
kind: ConfigMap
metadata:
    name: blessing-skin-env
data:
    TZ: Asia/Shanghai

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: blessing-skin-data
spec:
    accessModes:
        - ReadWriteOnce
    resources:
        requests:
            storage: 5Gi

---
apiVersion: v1
kind: Pod
metadata:
    name: blessing-skin
    labels:
        app: blessing-skin
spec:
    restartPolicy: Always
    containers:
        - name: blessing-skin
          image: ghcr.io/hiromuraki/containerized-service/blessing-skin:latest
          envFrom:
              - configMapRef:
                    name: blessing-skin-env
          ports:
              - containerPort: 80
                hostPort: 25580
                hostIP: 127.0.0.1
          volumeMounts:
              - name: blessing-skin-data
                mountPath: /app
    volumes:
        - name: blessing-skin-data
          persistentVolumeClaim:
              claimName: blessing-skin-data
