---
apiVersion: v1
kind: ConfigMap
metadata:
    name: nginx-proxy-manager-env
data:
    TZ: "Asia/Shanghai"

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: nginx-proxy-manager-data
spec:
    accessModes:
        - ReadWriteOnce
    resources:
        requests:
            storage: 1Gi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: nginx-proxy-manager-letsencrypt
spec:
    accessModes:
        - ReadWriteOnce
    resources:
        requests:
            storage: 1Gi

---
apiVersion: v1
kind: Pod
metadata:
    name: nginx-proxy-manager
    labels:
        app: nginx-proxy-manager
spec:
    restartPolicy: Always
    containers:
        - name: nginx-proxy-manager
          image: ghcr.io/hiromuraki/containerized-service/nginx-proxy-manager:latest
          envFrom:
              - configMapRef:
                    name: nginx-proxy-manager-env
          ports:
              - containerPort: 80
                hostPort: 80
                hostIP: 127.0.0.1
              - containerPort: 443
                hostPort: 443
                hostIP: 127.0.0.1
              - containerPort: 81
                hostPort: 81
                hostIP: 127.0.0.1
          volumeMounts:
              - name: data
                mountPath: /data
              - name: letsencrypt
                mountPath: /etc/letsencrypt
    volumes:
        - name: data
          persistentVolumeClaim:
              claimName: nginx-proxy-manager-data
        - name: letsencrypt
          persistentVolumeClaim:
              claimName: nginx-proxy-manager-letsencrypt
