---
apiVersion: v1
kind: ConfigMap
metadata:
    name: forgejo-env
data:
    USER_UID: "1000"
    USER_GID: "1000"
    TZ: "Asia/Shanghai"
    FORGEJO__server__ROOT_URL: "https://git.daveny.top/"
    FORGEJO__server__DOMAIN: "git.daveny.top"
    FORGEJO__server__SSH_DOMAIN: "git.daveny.top"
    FORGEJO__server__HTTP_PORT: 3000
    FORGEJO__server__SSH_PORT: 2222

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: forgejo-data
spec:
    accessModes:
        - ReadWriteOnce
    resources:
        requests:
            storage: 5Gi

---
apiVersion: v1
kind: Pod
metadata:
    name: forgejo
    labels:
        app: forgejo
spec:
    restartPolicy: Always
    containers:
        - name: forgejo
          image: ghcr.io/hiromuraki/containerized-service/forgejo:latest
          envFrom:
              - configMapRef:
                    name: forgejo-env
          ports:
              - containerPort: 3000
                hostPort: 3000
                hostIP: 127.0.0.1
              # 对应 PublishPort=2222:22 (监听所有网卡)
              # 2222 SSH 端口不方便反代，且 SSH 本身足够安全，所以直接监听所有网口即可
              - containerPort: 22
                hostPort: 2222
          volumeMounts:
              - name: forgejo-data
                mountPath: /data
    volumes:
        - name: forgejo-data
          persistentVolumeClaim:
              claimName: forgejo-data
